version: "3.1"

services:
  api:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    command: sh -c 'npm install && npm run watch'
    depends_on:
      - mysql
    networks:
      - api-network

  
  mysql:
    image: mysql:8.0
    container_name: app_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT_MYSQL}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_MYSQL}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_MYSQL}
      MYSQL_PASSWORD: ${DB_PASSWORD_MYSQL}
      MYSQL_USER: ${DB_USER_MYSQL}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - api-network
    

networks:
  api-network:
    driver: bridge

volumes:
  mysql_data: